### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ElonMuskIdiot** [unfuncaptcha/tguess#1]
Hi, please help me, I don't understand how to run this correctly, can you write in more detail? Do I need to run through Visual Studio or NodeJS? And does this code work for you?

**Comment by ElonMuskIdiot** [comment]
And where should I register this code? 

![image](https://github.com/unfuncaptcha/tguess/assets/167176018/f6d1283c-f7a3-4c9b-ad7a-5b6be6b85467)

**Comment by ElonMuskIdiot** [comment]
What data do I need to enter for this project to work?

**Comment by spearphishing** [comment]
This is an NPM package, so you will need to install it in whatever JavaScript environment you're working in.

You would use the package in your `index.js`/other `.js` files you want to generate guesses/tguesses in.

You need to provide your guess, a session token, and the content from the `dapib_script` url provided by Arkose Labs.

**Comment by ElonMuskIdiot** [comment]
![image](https://github.com/unfuncaptcha/tguess/assets/167176018/2a6869ff-eada-4f97-afce-ec745d0fe8a5)
![image](https://github.com/unfuncaptcha/tguess/assets/167176018/90a1d008-fd80-4cf2-bcd8-47e9fe64b91f)
![image](https://github.com/unfuncaptcha/tguess/assets/167176018/2b52cad3-0945-46dd-b88f-532e0b18ad85)

Here is my folder, where do I need to enter the session token and script? And what kind of file should I run then so that the script works?

**Comment by ElonMuskIdiot** [comment]
I use Visual studio

**Comment by spearphishing** [comment]
You don't clone the package repo unless you know what you're doing. You can install the package into your own project ([example here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment#using_npm)) using:

```
npm install tguess
```

After installing, you can import `tguess` like any other NodeJS package.
