### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ElonMuskIdiot** [unfuncaptcha/tguess#2]
Can you record on video how to start it and how it works?

**Comment by ElonMuskIdiot** [comment]
Here is my package.json file

![image](https://github.com/unfuncaptcha/tguess/assets/167176018/bbc3b109-138d-4cf1-8060-ab897d6ece78)

**Comment by ElonMuskIdiot** [comment]
Here are the startup errors

![image](https://github.com/unfuncaptcha/tguess/assets/167176018/ec8c1e4b-ba85-471b-a3cd-9aeaac3d24a5)

![image](https://github.com/unfuncaptcha/tguess/assets/167176018/3ed88bbf-6615-4a57-85b9-fb7a9e154e65)

**Comment by ElonMuskIdiot** [comment]
What should I do with it? I don't understand at all, where should I add it?

![image](https://github.com/unfuncaptcha/tguess/assets/167176018/9e6b7364-9b5c-46ab-b353-617bf54b9df0)

**Comment by spearphishing** [comment]
DM me on telegram, I'll walk you through how to use this package.

https://t.me/killchains
